[package]
name = "rattler-bin"
version.workspace = true
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "Rust binary for common Conda operations"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[[bin]]
name = "rattler"
path = "src/main.rs"

[features]
default = ["native-tls"]
native-tls = ["reqwest/native-tls", "rattler/native-tls", "rattler_repodata_gateway/native-tls", "rattler_networking/native-tls"]
rustls-tls = ["reqwest/rustls-tls", "rattler/rustls-tls", "rattler_repodata_gateway/rustls-tls", "rattler_networking/rustls-tls"]

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.2", features = ["derive"] }
console = { version = "0.15.7", features = ["windows-console-colors"] }
dirs = "5.0.1"
futures = "0.3.28"
indicatif = "0.17.5"
itertools = "0.10.5"
once_cell = "1.18.0"
rattler = { version = "0.3.0", path = "../rattler", default-features = false }
rattler_networking = { version = "0.3.0", path = "../rattler_networking", default-features = false }
rattler_conda_types = { version = "0.3.0", path = "../rattler_conda_types" }
rattler_repodata_gateway = { version = "0.3.0", path = "../rattler_repodata_gateway", features = ["sparse"], default-features = false }
rattler_solve = { version = "0.3.0", path = "../rattler_solve" }
rattler_virtual_packages = { version = "0.3.0", path = "../rattler_virtual_packages" }
reqwest = { version = "0.11.18", default-features = false }
tokio = { version = "1.28.2", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
serde_json = "1.0.70"

[package.metadata.release]
# Dont publish the binary
release = false
