[package]
name = "rattler-bin"
version = "0.1.0"
edition = "2021"
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "Rust binary for common Conda operations"
categories = ["conda"]
homepage = "https://github.com/mamba-org/rattler"
repository = "https://github.com/mamba-org/rattler"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rattler"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.44"
clap = { version = "4.0.13", features = ["derive"] }
console = { version = "0.15.5", features = ["windows-console-colors"] }
dirs = "4.0.0"
futures = "0.3.17"
indicatif = "0.17.3"
itertools = "0.10.3"
once_cell = "1.17.1"
rattler = { path = "../rattler" }
rattler_conda_types = { version = "0.1.0", path = "../rattler_conda_types" }
rattler_repodata_gateway = { version = "0.1.0", path = "../rattler_repodata_gateway" }
rattler_solve = { version = "0.1.0", path = "../rattler_solve" }
rattler_virtual_packages = { version = "0.1.0", path = "../rattler_virtual_packages" }
rattler_shell = { version = "0.1.0", path = "../rattler_shell" }
reqwest = "0.11.14"
tokio = { version = "1.21.1", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
